### ISSUE TITLE
Add host failing on 1.9.0 - IPVersion not set

### ISSUE THREAD

**Issue by a10kiloham** [evaneaston/udm-host-records#1]
Thanks for sharing these. It worked great until today when I upgraded to 1.9.0. Seems that the IP Version must be set for ipv4?

`{
 "detail": "",
 "error": 1,
 "message": ".dnsForwarder.hostRecords.address.version: IPVersion not set",
 "statusCode": 400
}`

**Comment by evaneaston** [comment]
Would you mind running the command:

`ubios-udapi-client GET -r /services | jq '.dnsForwarder.hostRecords[] | setpath(["address", "address"]; "redacted") | setpath(["hostName"]
; "redacted")'`

This should get me everything that is stored under `dnsForwarder.hostRecords` and remove your IP and hostName values for privacy.  I'm curious to see what other properties were added and what their values are.

**Comment by a10kiloham** [comment]
https://github.com/evaneaston/udm-host-records/pull/2 fixes it, although i suppose it could be done more elegantly with a command line option :)

**Comment by a10kiloham** [comment]
`{
  "address": {
    "address": "redacted",
    "origin": null,
    "version": "v4"
  },
  "hostName": "redacted",
  "registerNonQualified": true
}
{
  "address": {
    "address": "redacted",
    "origin": null,
    "version": "v4"
  },
  "hostName": "redacted",
  "registerNonQualified": false
}
{
  "address": {
    "address": "redacted",
    "origin": null,
    "version": "v4"
  },
  "hostName": "redacted",
  "registerNonQualified": true
}
{
  "address": {
    "address": "redacted",
    "origin": null,
    "version": "v4"
  },
  "hostName": "redacted",
  "registerNonQualified": true
}`

**Comment by evaneaston** [comment]
Thanks.  So they just added a version, presumably either v4 or v6.  Let me see if I can include the version attribute in calls to a server running 1.8.6.

**Comment by a10kiloham** [comment]
cool, thx

**Comment by evaneaston** [comment]
Confirmed that it lets you add the `"version": "v4"` attribute to the `"address"` records on a 1.8.6 FW UDMPro.  Thanks for #2.  I'll roll it in once I can add some simple command line option.

**Comment by evaneaston** [comment]
Fixed with latest 1.0 release.
