### ISSUE TITLE
configuration not solved

### ISSUE THREAD

**Issue by msavazzi** [evaneaston/udm-host-records#6]
evaneaston sorry to bother but I'm confused on your scripts.
I've added a line like this:
```
./add-host-record.sh c240dn.savazzi.eu 192.168.1.15
./add-host-record.sh c240dn 192.168.1.15

```
but on the pc when I run the nslookup I get conflicting results:

```
C:\Users\massi>nslookup
Default Server:  UnKnown
Address:  192.168.1.1


> c240dn
Server:  UnKnown
Address:  192.168.1.1


*** UnKnown can't find c240dn: Non-existent domain
> c240dn.savazzi.eu
Server:  UnKnown
Address:  192.168.1.1


Name:    c240dn.savazzi.eu
Address:  192.168.1.15


>

```

how is it possible? what am I doing wrong?

**Comment by evaneaston** [comment]
I don't have an answer, but because the criteria for updating hostRecords isn't clear, this repo can't offer to solve the DNS via UDM problem.   I'm deprecating the repo.
