### ISSUE TITLE
Broken on UniFi OS UDM Pro 1.11.4 with controller 7.1.61

### ISSUE THREAD

**Issue by gashinov** [evaneaston/udm-host-records#7]
Not working after controller update to 7.1.61.

 ```
./add-host-record.sh srv-01.local 172.16.20.11
host=srv-01.local
ip=172.16.20.11
ipVersion=v4
regNonQual=true
jq: parse error: Invalid numeric literal at line 1, column 8
Request failed: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```

**Comment by evaneaston** [comment]
Absent a PR to work with old and new versions, I think it's time to deprecate this repo entirely.

I don't know the circumstances that result in them resetting things.  So I don't know when it make sense to re-update host records.  And it doesn't appear that there's a hook to leverage to update host entries whenever they rebuild things.

I gave up a while a go and started running my one DNS server locally.

So, I'm sorry, but I'm deprecating this repo.
